sonar.projectKey=ProyectResponsable
sonar.projectName=ProyectResponsable
sonar.projectVersion=0.1
sonar.sources=app/http/controllers/ResponsableController.php
sonar.exclusions=app/http/controllers/ResponsableController.php